pipeline {
  agent {
    docker {
      image 'maven:3-alpine'
      args '-v /root/.m2:/root/.m2'
    }
  }
  
  stages {
    stage('Build'){
      steps{
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage('tests'){
      steps{
        sh 'mvn test'
        sh "mkdir -p output"
        writeFile file: "output/usefulfile.txt"
      }
    }
  }
}
